### ISSUE TITLE
Criação de Views e Rotas

### ISSUE THREAD

**Issue by apandalima** [kaspaulina/ES2#5]
`Configurar as rotas e as views para o projeto`

**ROTAS:** 

> tarefas

- [x] Definir as rotas para a página inicial

- [ ] Definir as rotas para as diferentes seções do dashboard
    - insigths
    - candidatos
    - partidos
    - municípios
- [ ] Configurar as rotas para as APIs

- [ ] Definir as rotas para o Manual do Sistema

**VIEWS:** 

> tarefas

- [ ] Criar a view da página inicial

- [ ] Criar as views para exibir os dados do dashboard

- [ ] Criar as views para os filtros e outras funcionalidades interativas

- [ ] Criar as views para o Manual do Sistema

**Comment by evertonse** [comment]
Feito
